development:
    adapter:  postgresql
    host:     localhost
    encoding: unicode
    database: drone_brain_development
    pool:     5

test:
    adapter:  postgresql
    host:     localhost
    encoding: unicode
    database: drone_brain_test
    pool:     5
